### ISSUE TITLE
GET /agent_groups/{id} should include associated policies in response

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1302]
Nowadays the response of GET /agent_groups/{id} is:

```
{
    "id": "e92037f1-0927-4445-88bf-371b51cb8ed1",
    "name": "first_connection_group",
    "description": "This is an agent group",
    "tags": {
        "multiple": "policies"
    },
    "ts_created": "2022-06-15T15:13:07.71225Z",
    "matching_agents": {
        "online": 0,
        "total": 7
    }
}
```

So it is not possible to know how many and which policies are associated with this group.

The purpose of this task is to include in the response of this endpoint a list of all policies linked to the group.

Expected part to be included:

```
"policy_state": {
            "policy_01_id": {
                "datasets":  {
                    "id: "dataset_associated_id",
                    "status": "dataset_associated_status"
               },
                "name": "policy_name"
                                    },
            "policy_02_id": {
                "datasets": {
                    "id: "dataset_associated_id",
                    "status": "dataset_associated_status"
               },
                "name": "policy_name"
                                    }
                        }
```

**Comment by manrodrigues** [comment]
> @weyrick @rboucher-ns1 @gpazuch @mclcavalcante @manrodrigues
> 
> I am a bit concerned with the following approach, the agent group has no direct association with the policies.
> 
> I think we need a different approach, I am thinking we just need an endpoint to gather the relationships and display them as requested. Similar to what we have in a ElasticSearch query.
> 
> From what I am seeing in the issues of this epic, we want a listing of all related entities and the corresponding status.
> 
> /relationships?groupId=group1
> 
> ```json
> [
> {
>   "agent": { // agentID, heartbeatStatus, tags},
>   "policy": { // policyID, statusOnPktvisor (from agent) },
>   "sink": { // sinkId, scrapingStatus },
> },...,]...
> ```
> 
> what do you guys think?

I think it's a much smarter idea than my first one. I agree :)

**Comment by rboucher-ns1** [comment]
I like this idea, though I wonder if the relationship structure shouldn't be a little different:
```
{
   "agents": [
      { // agentID, heartbeatStatus, tags}
   ],
   "policies": [
      { // policyID, statusOnPktvisor (from agent), "sinks": [ { // sinkId, scrapingStatus } ] }
   ]
}
```
