### ISSUE TITLE
Register: terms of service acceptance email is being sent when a user tries to register an already registered account

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1405]
Each time the user tries to register an email already registered, the email confirming the terms of service is sent. Therefore, it seems that the registration process is having some steps redone.

Same email, different times/days:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/57f67876-885d-4ade-8e5d-61752cdc7c76)

**Comment by lpegoraro** [comment]
After reading and studying the code, I see that this is no low hanging fruit. But this can be addressed in the next epic for a Notification Center, to have all notifications addressed by that service. Relates to #1662
