### ISSUE TITLE
Policies: Improve the error message on yaml policy validation during the editing process:

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1451]
It's still needed to improve the error message on policy validation during the editing process:

![edit_json](https://user-images.githubusercontent.com/78241475/178273211-9f1c210a-d4ed-4092-bd44-4fc8fc5151af.gif)

_Originally posted by @manrodrigues in https://github.com/ns1labs/orb/issues/1018#issuecomment-1180399972_

**Comment by brunofariasdeo** [comment]
Hi @manrodrigues ,
This issue was already resolved in [this PR](https://github.com/ns1labs/orb/issues/1285)

![image](https://user-images.githubusercontent.com/42921279/179057717-e1c6958a-8485-442f-827e-60d307a7009d.png)

**Comment by manrodrigues** [comment]
No.. I changed the title to be more accurate.

On editing process of yaml policies (not json).. the message is not helpful

![error_policy_editing](https://user-images.githubusercontent.com/78241475/179579834-f6642804-82b9-40aa-af2b-8ac6d82d8120.gif)
