### ISSUE TITLE
UX design to expose pktvisor metrics in Orb UI

### ISSUE THREAD

**Issue by rboucher-me** [orb-community/orb#1513]

**Comment by rboucher-ns1** [comment]
Here is a sample of the data that the API endpoint will expose for a specific agent and a specific policy (the exact format might change from this example).
[pktvisor_window5_sample.txt](https://github.com/ns1labs/orb/files/9154618/pktvisor_window5_sample.txt)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/185679710-5ef095fd-3b66-4d61-aa99-f057dffb0bbd.png)

**Comment by gpazuch** [comment]
DHCP
![image](https://user-images.githubusercontent.com/1490938/185923199-68677130-b9ad-4639-b463-4ced18ac6a7f.png)

*rates
*wire_packets
*period

**Comment by gpazuch** [comment]
PACKETS
![image](https://user-images.githubusercontent.com/1490938/185923526-e79a8e7e-a56a-438c-86e4-cf8d7ce4bb9c.png)
*cardinals (deep_samples, etc)
*cardinality
*payload_size
*protocol
*rates
*tops

**Comment by gpazuch** [comment]
PCAP
![image](https://user-images.githubusercontent.com/1490938/185923755-05e673f0-553b-401b-8364-e20866fc777d.png)
*period
*cardinals

**Comment by gpazuch** [comment]
a more recent [sample output](https://gist.github.com/gpazuch/d83547d1e005ddb7ddeb14d0441cc063)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/186282753-f0b5cb8e-9583-456c-9a7d-cc3c45dea649.png)
