### ISSUE TITLE
Support `bearer_token` authentication for Prometheus sinks

### ISSUE THREAD

**Issue by rboucher-me** [orb-community/orb#1681]
Extend existing Prometheus sink authentication to support `bearer_token`, such as what is required by New Relic: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/

**Comment by lpegoraro** [comment]
Backend Issues TBD

- [ ] Sinks - API Support to create Sink Config with Bearer_token, and store accordingly. ~ 3 SP
 Q1 : Should we encrypt?
- [ ] Sinker - Enable bearer token in Authentication Header remoteWriteToPrometheus ~ 3 SP

**Comment by lpegoraro** [comment]
Somehow the info I added last week, vanished from GitHub... readding

Backend
- [ ] Sinks: API Support for receiveing the bearer_token and store accordingly.
Q1: Do we need to encrtypt the bearer_token? 
- [ ] Sinker: Support bearer token in authentication header, if stored version > v2.26.
