### ISSUE TITLE
Tests: elaborate a performance plan

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1709]
- Check which tools and metrics for performance testing
- describe the principals scenarios to be covered by performance tests

**Comment by pfbrasi** [comment]
**JMeter:** Java open-source software. JMeter to analyze and measure the performance of web applications or a variety of services.
Advantages of JMeter

-     Has GUI for less technical users
-     It has a long list of supported protocols and plugins
-     Completely open-source and free
-     Plenty of online support
-     Offers dynamic HTML reports

Disadvantages of JMeter

-     **Scripting**  Requires someone with deep knowledge of JMeter elements and functionality.
-     **Protocol Support**  Cannot execute JavaScript.  No support for technologies that are used to build dynamic applications, like AJAX, JavaScript, Flash, etc.
-     **Support for Real Browsers**  Does not render web elements in a real browser.
-     **Executing Large Load Tests**  Requires extensive manual work to carry out tests with a large number of users.


**Gatling** is a load testing tool which can be used for your integrated development environment, version control systems and continuous integration solutions. Gatling is written in Scala, which allows you to run it on any system. It supports HTTP protocol and also a few other protocols as well.

Advantages of Gatling

-     Offers integration into CI/CD pipelines
-     It needs fewer third party plugins
-     Lightweight and consumes smaller memory
-     Has recording functionality
-     Offers real-time test monitoring

Disadvantages of Gatling

-     Has a smaller open source community
-     No GUI for non-developers



<html><body>


Features | Gatling | JMeter
-- | -- | --
Writing test scenarios | Requires knowledge of basic Scala and DSL language understanding. | GUI helps to create thread groups and write easy to use test scenarios.
Test runs | Load test can be run from your local machine or dedicated servers. | It requires local machine or dedicated servers for heavy traffic.
Geo-distributed Load Test | Requires setup of AWS or GCP servers on dedicated location to test. | Requires setup of AWS or GCP servers on dedicated location to test.
Documentation and Support | Gatling requires familiarity with DSl and Scala to understand documentation better. | JMeter has the best documentation as it is the oldest and matured tool.
Pricing | Open-source and free | Open-source and free
Integration with CI/CD Jenkins | Yes | Yes


</body>
</html>

**Comment by pfbrasi** [comment]
Lighthouse report: 
[Lighthouse Report Viewer 09-16-22.pdf](https://github.com/ns1labs/orb/files/9587147/Lighthouse.Report.Viewer.09-16-22.pdf)

**Comment by pfbrasi** [comment]
Possible scenarios that can be used for performance tests on Orb
![image](https://user-images.githubusercontent.com/83239935/191364507-a863bfed-b391-449f-a97d-a32053c524e4.png)
