### ISSUE TITLE
Sinks fails when some agent has a tag which key is one of the reserved label words

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1786]
Related with https://github.com/ns1labs/orb/issues/1199

When some agent has a tag which key is one of the reserved label words (agent, handler, policy, policy_id, etc..) the sink will fail and no more metrics will be scraped into that sink.
This happens because the tags are labels.
Here we can see the error get when I inserted the tag "policy:test" on my agent:

```
    "tags": {
        "": ""
    },
    "state": "error",
    "error": "expected 2xx status code: actual=400, body=received a series with duplicate label name, label: 'policy' series: 'dns_period_start_ts{agent=\"test_agent_name_lwiEWQrEyM\", agent_id=\"468d8ba4-d619-4de1-9469-1c1f200a0f00\", handler=\"test_policy_name_hOLVXPqjPo-default_pcap-default_dns_xyO\", instance=\"test_agent_name_l' (err-mimir-duplicate-label-names)\n",
    "backend": "prometheus",
    "config": {
```

My suggestion is that "tags" be a label and the choice of tags are within this filter, instead of the key of each tag being at the label level like agent, policy, etc.

**Comment by mclcavalcante** [comment]
We can add a prefix for agent tags before adding to Prometheus labels, for example:
agent tag is policy:test and we will add the label as tag_policy:test

As @manrodrigues suggested, it can be done by adding this prefix to all labels inherited from agent tags even if it isn't a reserved word for consistency
