### ISSUE TITLE
Agent View: policies column must be yellow colored if the only reason for not all policies are running is no_match

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#1797]
On the same way as #1789, on policies column:

- if no policies are linked -> grey 
- if all policies linked to the agent are running -> green
- if at least one of the policies linked to the agent is not run because of no_match AND no policy really fails to be applied -> yellow
- if at least one of the policies linked to the agent has status "failed_to_apply) -> red

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/b1627b2a-31eb-4836-959f-14e4a42aae11)

**Comment by gpazuch** [comment]
duplicated by #1789
