### ISSUE TITLE
Agent Groups: Although an error message appears, it is possible to create two identical key and value pairs

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#183]
A error message is being displayed but double key-value creation is allowed

Check: https://drive.google.com/file/d/1MvdknGxMO03T9Npfqo35hUCbqvXp44ib/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

**Comment by iatdaitan** [comment]
![image](https://user-images.githubusercontent.com/86745196/140174209-0b2ac3d3-4030-459e-8873-39fc7fe8af8f.png)
