### ISSUE TITLE
Agent Groups: Unable to edit existing agent group

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#191]
Check: https://drive.google.com/file/d/1RJw6d3tK2z1SbNaXeH9hO0rnyULIaXOS/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

**Comment by gpazuch** [comment]
Not sure if related or not.

I noticed after creating agent, I could update agent with new tags, but could not remove tags from said agent
