### ISSUE TITLE
[QUESTION] Is orb multi-tenant?

### ISSUE THREAD

**Issue by tom342178** [orb-community/orb#2283]
To what extent has multi-tenant been architected into the orb solution?

Would I need to stand up  a complete orb stack for each of my tenants in order to isolate **access** to the metric from their devices?

**Comment by weyrick** [comment]
Hi @tom342178, no you would not need to stand up new stacks. Orb control plane has "simple" multi-tenancy (there is real tenancy but only one user per tenant, currently). Also, if your goal is just isolating metrics then depending on your use case you may be able to use a single tenant with multiple Data Sets and Sinks.

You can try this out for yourself right now by heading over to https://orb.live. When you register a new account, you are creating a tenant.

**Comment by tom342178** [comment]
thanks @weyrick
