### ISSUE TITLE
pktvisor-cli has this error "version `GLIBC_2.32' not found "

### ISSUE THREAD

**Issue by lixinchina1** [orb-community/orb#2508]
**Describe the bug**
# docker exec -it dockercompose_orb-agent_1 bash
root@dns01:/# dockercompose_orb-agent_1^C
root@dns01:/# pktvisor-cli
pktvisor-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pktvisor-cli)
pktvisor-cli: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pktvisor-cli)

this happens on ubuntu host 
Agent Version
0.26.0-develop-c9bcef4
PKTVISOR
Version: 4.4.0-ns1-develop-18764e5

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by manrodrigues** [comment]
@lixinchina1 we have it fixed in our dev environment both for orb_agent and pktvisor:

Tags:

`pktvisor: 4.4.0-develop-0a280c1` 
`orb_agent: 0.27.0-develop-fdbacb8`

**Comment by lixinchina1** [comment]
awesome and thx @manrodrigues  we will test it out (folks doing agent custom build are out this week so won't expect any progress till next week)

**Comment by manrodrigues** [comment]
NJ confirmed it working. I'm closing the issue then. Feel free to reopen if you observe anything different, @lixinchina1

**Comment by lixinchina1** [comment]
sounds good; ty for making the fix @manrodrigues
