### ISSUE TITLE
Create new landing page to create a new password

### ISSUE THREAD

**Issue by iatdaitan** [orb-community/orb#525]

**Comment by gpazuch** [comment]
@iatdaitan 
Is this the change password page the user should be redirected to after receiving the link for new password, after `Forgot Password` flow?

**Comment by manrodrigues** [comment]
request password button is not working. Note that no request is sent

![reset-password-button](https://user-images.githubusercontent.com/78241475/146610119-a1e728fc-6654-420b-9d9b-25bcc4b15db1.gif)

**Comment by manrodrigues** [comment]
once request new password is not working (as we discussed... maybe related with https://github.com/ns1labs/orb.live/issues/3), i'm not able to test this new page

**Comment by manrodrigues** [comment]
We need to have a page to reset the password since now the email is working:

![page_reset](https://user-images.githubusercontent.com/78241475/171902585-f245e8ca-3255-4888-8848-412229308d99.gif)
