### ISSUE TITLE
Manage agent taps from control plane/UI

### ISSUE THREAD

**Issue by iatdaitan** [orb-community/orb#543]
Right now these are created only at the agent by config file. We should be able to create/manage from Orb. Requires RPC communication.

**Comment by gpazuch** [comment]
@iatdaitan would this translate as a button or checkbox in agent form, where the user could select bootstrapping the agent via Orb?

**Comment by weyrick** [comment]
This would be part of our expanded functionality on the Agent Detail view. We should be listing the current taps available on that agent, and this ticket would add the functionality that they can create a new Tap as well.

**Comment by gpazuch** [comment]
relates to [#547](https://github.com/ns1labs/orb/issues/547)
blocked until [#520](https://github.com/ns1labs/orb/issues/520) (?)

**Comment by gpazuch** [comment]
I'm a bit unsure on how to estimate this.

**Comment by iatdaitan** [comment]
@gpazuch ignore for now. Let's do a refinement session first.
