### ISSUE TITLE
Create Opentelemetry integration with Orb

### ISSUE THREAD

**Issue by iatdaitan** [orb-community/orb#544]
Some early designs

![Orb diagrams - page 19](https://user-images.githubusercontent.com/195691/142463666-0d5088d2-8483-4d5e-9ed8-c2a795021fdc.png)
![Orb diagrams - page 18](https://user-images.githubusercontent.com/195691/142463678-367773a6-b94e-4820-9567-a96f9d340c35.png)

**Comment by weyrick** [comment]
https://opentelemetry.io/docs/collector/configuration/#authentication

**Comment by weyrick** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md

**Comment by weyrick** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by weyrick** [comment]
https://github.com/open-telemetry/opentelemetry-collector

**Comment by weyrick** [comment]
https://opentelemetry.io/docs/collector/

**Comment by weyrick** [comment]
https://opentelemetry.io/docs/reference/specification/overview/#metric-signal

**Comment by dscabral** [comment]
![image](https://user-images.githubusercontent.com/87036053/144057015-2769529a-c069-4a97-8bf2-22bcda7f5875.png)
