### ISSUE TITLE
(Tech Debt - Double identify) Instrumentation for Fleet Service Metrics

### ISSUE THREAD

**Issue by iatdaitan** [orb-community/orb#551]
*Tech Debt:*
- Identify job is being done inside service but is needed before for labeling in service metrics
- Currently we are repeating authentication twice: inside service and in metrics

Implemented metrics for:
- number of requests 
- request latency

**Comment by weyrick** [comment]
This needs some design first - we need to understand what we want to expose. Also we need to understand what will be intended for operators vs what we can expose as part of the product to end users
