### ISSUE TITLE
Agents: heartbeat update after deleting all datasets needs to be faster

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#897]
Hearttbeat change takes a long time to update after deleting all datasets (more than 2 minutes)

When all datasets are removed, it takes some seconds to this modification reflects on agent's heartbeat (backend problem), but it is failing the agent view:

![image](https://user-images.githubusercontent.com/78241475/155653843-fce31d2c-a367-4e1f-b9be-f3a2d074eb4d.png)

**Comment by iatdaitan** [comment]
@manrodrigues could you please check if this issue is fixed already?

**Comment by manrodrigues** [comment]
It's not fixed yet.. Deleting a dataset should immediately send new information to hb and update the state

![multiple_handlers](https://user-images.githubusercontent.com/78241475/180798378-48ee2517-7f2f-410d-abef-9a1123e816ed.gif)
